### ISSUE TITLE
🐛 Bug Report: Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [appwrite/docs#430] opened 2023-09-10 03:19 UTC
### 👟 Reproduction steps

Scroll to footer section and see twitter old logo

### 👍 Expected behavior

Twitter logo should be changed to X

### 👎 Actual Behavior

Twitter logo is updated recently and hasnt been updated on the site. I didnt find any issue related to this.

Screenshot
<img width="960" alt="Screenshot 2023-09-10 084717" src="https://github.com/appwrite/docs/assets/91591901/b44092bf-9f1e-4b76-a589-bfe00829a53e">

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-09-12 01:34
Closing as a duplicate of https://github.com/appwrite/appwrite/issues/6208

**Closed by stnguyen90** 2023-09-12 01:34 UTC
Labels: bug
